var sozluk = {
  "A Bit More":"biraz daha fazla",
  "A Bunch Of":" bir grup",
  "A Clear Conscience":" gönül rahatlığı",
  "A Dithering İdiot":"sarsak",
  "A Few":"az sayıda",
  "A Good Deal Of":" bir damla,birçok",
  "A Great Many":"pek çok , çok fazla",
  "A Leg Up":"destek,koltuk çıkma",
  "A Little Way Off ":"biraz uzakta ",
  "A Long Way Off":" çok uzak,çok uzakta",
  "A Modicum Of":"zerre kadar,az bir miktar",
  "A Must":"vazgeçilmez tercih, olmazsa olmazı",
  "A Pile Of":"yığın",
  "A Puff Of Smoke":" duman kümesi",
  "A Set Of ":" bir takım",
  "A Spate Of":"pek çok.bir süre",
  "A Taste":" bir tadımlık",
  "A Tough Nut":" çetin ceviz",
  "Abandon":"terk etmek",
  "Abandoned":"terkedilmiş, bırakılmı?, metruk.",
  "Abandoner":"başkasına mal bırakan kimse",
  "Abandonment":"terk, bırakılma, vazgeçme",
  "Abate":"azalmak,hafiflemek",
  "Abatement":"azaltma, hafifletme; azalma, hafifleme.",
  "Abattoir":"mezbaha, kesimevi",
  "Abbey":"manastır",
  "Abbot":"başrahip",
  "Abbrevation":"kısaltma",
  "Abbreviate":"kısaltmak.",
  "Abbreviated":"kısaltılmış",
  "Abbreviator":"kısaltma yapan kimse",
  "Abdicate":"(bir haktan) vazgeçmek, feragat etmek.",
  "Abdication":"feragat.tacını ve tahtını terketme.",
  "Abdomen":"karın",
  "Abdominal":"karna ait.",
  "Abdominally":"karınsal",
  "Abduct":"birisini kaçırmak",
  "Abduction":"kaçırma",
  "Abductor":" kaçıran kişi ( çoçuk vs)",
  "Abed":" yatakta (eski söyleniş)",
  "Aberrance-Aberrancy ":" sapma,sapıklık",
  "Aberrant":" normal olmayan,sapkın,doğru yoldan ayrılmış",
  "Aberrantly":" sapkın bir halde, anormal bir şekilde",
  "Aberrate":" beklenen durumdan sapmak",
  "Aberration":"sapma (doğru/doğal/normal olandan)",
  "Abet":"suç ortaklığı yapmak,yardım etmek",
  "Abhor":"nefret etmek,tiksinmek",
  "Abhorrence":"nefret,iğrenme",
  "Abhorrent":"nefret uyandıran, tiksindirici.",
  "Abhorrer":"tiksinen kimse",
  "Abide":"beklemek,sadık kalmak",
  "Abider":"bir yerin sakini",
  "Ability":"yetenek",
  "Abject":"kendini küçük düşüren,küçük düşürücü,rezil ,aşagılıyıcı",
  "Abjectly":"gurursuzca, kendini alçaltarak.",
  "Abjectness":" bayağılık,alçaklık",
  "Abjure":" tövbe etmek, yeminli terk ve feragat etmek",
  "Ablaze":"yanmakta,tutuşmakta",
  "Able":"muktedir",
  "Ablution":"aptes, gusül",
  "Ably":"iyi bir şekilde.",
  "Abnegate":" kaçmak (sorumluluktan), feda etmek",
  "Abnegation":"feragat etme,fedakarlık",
  "Abnormal":"anormal.",
  "Abnormally":"anormal bir şekilde",
  "Aboard":"(bir taşıtın)içinde olmak",
  "Abode":"ikametgâh, ev. bir yerde ikamet etmek",
  "Abolish":"iptal etmek,yürürlükten kaldırmak",
  "Abolishable":" feshedilebilir, iptal edilebilir",
  "Abolisher":" iptal eden kimse",
  "Abolition-Abolishment":"kaldırmak,fesh,iptal",
  "Abolitionist":"köleliğin kaldırılması yanlısı, iptal etme taraftarı",
  "Abominable":"iğrenç,tiksindirici",
  "Abominably":" tiksindirici bir şekilde",
  "Abominate":"nefret etmek, tiksinmek.",
  "Abomination":"nefret etme, tiksinme.",
  "Aboriginal":"yerli, bir ülkenin asıl yerlisi.",
  "Abortion":"kürtaj,düşük",
  "Abortive":"gelişmemiş,başarısız",
  "Abortively":" verimsiz bir şekilde,eksik olarak",
  "Abortiveness":" gelişmemişlik, başarısızlık",
  "Abound":" bol miktarda bulunmak",
  "Abounding":" bol,çok",
  "About":"1.hakkında 2.yaklaşık olarak,etrafında",
  "Above":"yukarıda",
  "Above All":"herşeyden en önemlisi",
  "Above And Beyond":"fazlasıyla, yeter de artar",
  "Aboveboard":"kanuna aykırı olmayan,yasal",
  "Abrasion":"aşınma,aşındırma",
  "Abrasive":"kaba,kırıcı",
  "Abreast":"yan yana, aynı hizada; başabaş.",
  "Abreast Of":"ayak uyduran,(herhagi bir konu hakkında) son gelişmelerden haberi olan",
  "Abridge":"kısaltmak, özetlemek.",
  "Abridged":" kısaltılmış versiyon",
  "Abridgement":"kısaltma, özet.",
  "Abroad":"yurt dışı",
  "Abrogate":"iptal etmek, feshetmek.",
  "Abrogation":"iptal, feshetme.",
  "Abrupt":"ani,beklenmedik",
  "Abruptly":"aniden,birdenbire",
  "Abruptness":"anilik,tutarsızlık",
  "Abscond":"kaçmak, sıvışmak.",
  "Absconder":" kaçak,firari",
  "Absence":"yokluk",
  "Absent":"1.yok 2.eksik",
  "Absent Minded":"unutkan,dalgın",
  "Absentee":" devamsız kimse,vazifede bulunmayan",
  };
  
function yenile() {
  div_tr = document.querySelector("#tr");
  div_en = document.querySelector("#en");
  toplam_kelime = Object.keys(sozluk).length;
  rastgele_sayi = Math.floor(Math.random() * toplam_kelime);  
  secilen_en = Object.keys(sozluk)[rastgele_sayi];
  secilen_tr = sozluk[Object.keys(sozluk)[rastgele_sayi]];
  div_en.innerHTML = secilen_en;
  div_tr.innerHTML = secilen_tr;
}
yenile()